name: Test

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        job:
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu

          # TODO: Tests on Windows requires gdal, but I don't know how to install it yet...
          # - os: windows-latest
          #   arch: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.job.os }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.arch }}

      - name: Install dependencies
        if: matrix.job.os == 'ubuntu-latest'
        run: sudo apt-get install -y gdal-bin

      - name: Cache temporary files
        uses: actions/cache@v4
        with:
          key: v1-temporary-files-${{ hashFiles('src/**/*.rs') }}
          restore-keys: |
            v1-temporary-files-
          path: tmp

      - name: Run test
        run: cargo test
